name: file_sharer
description: file_sharer
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.6.4
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
